/*

 HASHIDASPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 1 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0x7C,0x7C,0xFF,0xC7,0xFE,0xAA,0xFE,0x86,
  0x44,0xFF,0x7E,0xFF,0x99,0x99,0x3C,0x3C
};

/* End of HASHIDASPRITE.C */
