/*

 OKABEMOVESPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Okabe[] =
{
  0x7C,0x7C,0xFE,0xC6,0xFE,0xAA,0xFE,0x82,
  0x6C,0xFE,0xAA,0xFE,0xBA,0xFE,0x28,0x6C,
  0x7C,0x7C,0xFE,0xC6,0xFE,0xAA,0xFE,0x82,
  0x6C,0xFE,0xAA,0xFE,0xBA,0xFE,0x00,0x44
};

/* End of OKABEMOVESPRITE.C */
